//=============================================================================================
/**
 * @file	crc_loadcheck.h
 * @brief	CRCによる、セーブデータや通信の検査を管理するヘッダー
 * @author	k.ohno
 * @date	2007.12.3
 *
 */
//=============================================================================================
#ifndef	__CRC_LOADCHECK_H__
#define	__CRC_LOADCHECK_H__

#if CRC_LOADCHECK

#define CRCLOADCHECK_GMDATA_ID_SYSTEM_DATA  (0)
#define CRCLOADCHECK_GMDATA_ID_PLAYER_DATA  (0)
#define CRCLOADCHECK_GMDATA_ID_TEMOTI_POKE  (0)
#define CRCLOADCHECK_GMDATA_ID_TEMOTI_ITEM  (0)
#define CRCLOADCHECK_GMDATA_ID_EVENT_WORK  (0)   //検査不十分の為
#define CRCLOADCHECK_GMDATA_ID_POKETCH_DATA  (0)
#define CRCLOADCHECK_GMDATA_ID_SITUATION  (0)
#define CRCLOADCHECK_GMDATA_ID_ZUKANWORK  (0)
#define CRCLOADCHECK_GMDATA_ID_SODATEYA  (0)
#define CRCLOADCHECK_GMDATA_ID_FRIEND  (0)
#define CRCLOADCHECK_GMDATA_ID_MISC  (0)
#define CRCLOADCHECK_GMDATA_ID_FIELDOBJSV  (0)
#define CRCLOADCHECK_GMDATA_ID_UNDERGROUNDDATA  (0)
#define CRCLOADCHECK_GMDATA_ID_REGULATION  (0)
#define CRCLOADCHECK_GMDATA_ID_IMAGECLIPDATA  (0)
#define CRCLOADCHECK_GMDATA_ID_MAILDATA  (0)
#define CRCLOADCHECK_GMDATA_ID_PORUTODATA  (0)
#define CRCLOADCHECK_GMDATA_ID_RANDOMGROUP  (0)
#define CRCLOADCHECK_GMDATA_ID_FNOTE  (0)
#define CRCLOADCHECK_GMDATA_ID_TRCARD  (0)
#define CRCLOADCHECK_GMDATA_ID_RECORD  (0)
#define CRCLOADCHECK_GMDATA_ID_CUSTOM_BALL  (0)
#define CRCLOADCHECK_GMDATA_ID_PERAPVOICE  (0)
#define CRCLOADCHECK_GMDATA_ID_FRONTIER  (0)
#define CRCLOADCHECK_GMDATA_ID_SP_RIBBON  (0)
#define CRCLOADCHECK_GMDATA_ID_ENCOUNT  (0)
#define CRCLOADCHECK_GMDATA_ID_WORLDTRADEDATA  (0)
#define CRCLOADCHECK_GMDATA_ID_TVWORK  (1)
#define CRCLOADCHECK_GMDATA_ID_GUINNESS  (1)
#define CRCLOADCHECK_GMDATA_ID_WIFILIST  (0)
#define CRCLOADCHECK_GMDATA_ID_WIFIHISTORY  (1)
#define CRCLOADCHECK_GMDATA_ID_FUSHIGIDATA  (1)
#define CRCLOADCHECK_GMDATA_ID_POKEPARKDATA  (1)
#define CRCLOADCHECK_GMDATA_ID_CONTEST  (1)
#define CRCLOADCHECK_GMDATA_ID_PMS  (1)
#define CRCLOADCHECK_GMDATA_ID_EMAIL  (1)
#define CRCLOADCHECK_GMDATA_ID_WFHIROBA  (0)
#define CRCLOADCHECK_GMDATA_ID_BOXDATA  (0)
#define CRCLOADCHECK_ESV_DENDOU  (0)
#define CRCLOADCHECK_ESV_FRONTIER  (0)
#define CRCLOADCHECK_ESV_BATTLE_REC_MINE  (0)
#define CRCLOADCHECK_ESV_BATTLE_REC_DL_0  (0)
#define CRCLOADCHECK_ESV_BATTLE_REC_DL_1  (0)
#define CRCLOADCHECK_ESV_BATTLE_REC_DL_2  (0)


#else //CRC_LOADCHECK

#define CRCLOADCHECK_GMDATA_ID_SYSTEM_DATA  (0)
#define CRCLOADCHECK_GMDATA_ID_PLAYER_DATA  (0)
#define CRCLOADCHECK_GMDATA_ID_TEMOTI_POKE  (0)
#define CRCLOADCHECK_GMDATA_ID_TEMOTI_ITEM  (0)
#define CRCLOADCHECK_GMDATA_ID_EVENT_WORK  (0)
#define CRCLOADCHECK_GMDATA_ID_POKETCH_DATA  (0)
#define CRCLOADCHECK_GMDATA_ID_SITUATION  (0)
#define CRCLOADCHECK_GMDATA_ID_ZUKANWORK  (0)
#define CRCLOADCHECK_GMDATA_ID_SODATEYA  (0)
#define CRCLOADCHECK_GMDATA_ID_FRIEND  (0)
#define CRCLOADCHECK_GMDATA_ID_MISC  (0)
#define CRCLOADCHECK_GMDATA_ID_FIELDOBJSV  (0)
#define CRCLOADCHECK_GMDATA_ID_UNDERGROUNDDATA  (0)
#define CRCLOADCHECK_GMDATA_ID_REGULATION  (0)
#define CRCLOADCHECK_GMDATA_ID_IMAGECLIPDATA  (0)
#define CRCLOADCHECK_GMDATA_ID_MAILDATA  (0)
#define CRCLOADCHECK_GMDATA_ID_PORUTODATA  (0)
#define CRCLOADCHECK_GMDATA_ID_RANDOMGROUP  (0)
#define CRCLOADCHECK_GMDATA_ID_FNOTE  (0)
#define CRCLOADCHECK_GMDATA_ID_TRCARD  (0)
#define CRCLOADCHECK_GMDATA_ID_RECORD  (0)
#define CRCLOADCHECK_GMDATA_ID_CUSTOM_BALL  (0)
#define CRCLOADCHECK_GMDATA_ID_PERAPVOICE  (0)
#define CRCLOADCHECK_GMDATA_ID_FRONTIER  (0)
#define CRCLOADCHECK_GMDATA_ID_SP_RIBBON  (0)
#define CRCLOADCHECK_GMDATA_ID_ENCOUNT  (0)
#define CRCLOADCHECK_GMDATA_ID_WORLDTRADEDATA  (0)
#define CRCLOADCHECK_GMDATA_ID_TVWORK  (0)
#define CRCLOADCHECK_GMDATA_ID_GUINNESS  (0)
#define CRCLOADCHECK_GMDATA_ID_WIFILIST  (0)
#define CRCLOADCHECK_GMDATA_ID_WIFIHISTORY  (0)
#define CRCLOADCHECK_GMDATA_ID_FUSHIGIDATA  (0)
#define CRCLOADCHECK_GMDATA_ID_POKEPARKDATA  (0)
#define CRCLOADCHECK_GMDATA_ID_CONTEST  (0)
#define CRCLOADCHECK_GMDATA_ID_PMS  (0)
#define CRCLOADCHECK_GMDATA_ID_EMAIL  (0)
#define CRCLOADCHECK_GMDATA_ID_WFHIROBA  (0)
#define CRCLOADCHECK_GMDATA_ID_BOXDATA  (0)
#define CRCLOADCHECK_ESV_DENDOU  (0)
#define CRCLOADCHECK_ESV_FRONTIER  (0)
#define CRCLOADCHECK_ESV_BATTLE_REC_MINE  (0)
#define CRCLOADCHECK_ESV_BATTLE_REC_DL_0  (0)
#define CRCLOADCHECK_ESV_BATTLE_REC_DL_1  (0)
#define CRCLOADCHECK_ESV_BATTLE_REC_DL_2  (0)






#endif //CRC_LOADCHECK

#endif //__CRC_LOADCHECK_H__

