#!/bin/bash
set -e

args=("$@")
fname=

for ((i=0; i<${#args[@]}; i++)); do
    case "${args[$i]}" in
    -o)
        fname="${args[$i+1]}"
        ;;
    esac
done

wine "$0".exe "${args[@]}"

depfile="$(basename "$fname" | rev | cut -d. -f2- | rev).d"
if [ -f "$depfile" ]; then
    sed -i -e 's@Z:@@g' "$depfile"
fi
