#!/bin/bash
set -e

args=("$@")
fname=

for ((i=0; i<${#args[@]}; i++)); do
    case "${args[$i]}" in
    -include)
        args[$i+1]="Z:${args[$i+1]}"
        ;;
    -o)
        fname="${args[$i+1]}"
        ;;
    -precompile)
        fname="${args[$i+1]}"
        ;;
    esac
done

wine "$0".exe "${args[@]}"

depfile="$(basename "$fname" | rev | cut -d. -f2- | rev).d"
[ "$depfile" = "precompile_cc.d" ] && depfile="precompile.d"
if [ -f "$depfile" ]; then
    sed -i -e 's@Z:@@g' "$depfile"
fi
