//---- コンバータ：SPAConv.exe  Version 1.13

#ifndef __FRONTIER_PARTICLE_LST_H__
#define __FRONTIER_PARTICLE_LST_H__

//test_001.hのsprリソース定義
#define TEST_001_000_EC001_1A		0
#define TEST_001_000_EC001_1B		1
//test_001.spa内のリソース個数
#define TEST_001_SPAMAX	(2)

//test_002.hのsprリソース定義
#define TEST_002_000_EC001_1B		0
#define TEST_002_000_EC001_1C		1
#define TEST_002_000_EC001_1D		2
//test_002.spa内のリソース個数
#define TEST_002_SPAMAX	(3)

//stage.hのsprリソース定義
#define STAGE_BS_KAMITAPE_L		0
#define STAGE_BS_KAMITAPE_R		1
#define STAGE_BS_KAMI_01_L		2
#define STAGE_BS_KAMI_01_R		3
#define STAGE_BS_KAMI_02_L1		4
#define STAGE_BS_KAMI_02_L2		5
#define STAGE_BS_KAMI_02_R1		6
#define STAGE_BS_KAMI_02_R2		7
#define STAGE_BS_PASYAPASYA01		8
#define STAGE_BS_PASYAPASYA02		9
#define STAGE_BS_PASYAPASYA02_BG		10
#define STAGE_BS_PASYAPASYA03		11
#define STAGE_BS_PASYAPASYA03BG		12
#define STAGE_BS_PASYA_01		13
#define STAGE_BS_PASYA_02		14
#define STAGE_BS_PASYA_BG		15
#define STAGE_BS_SPOT00		16
#define STAGE_BS_SPOT00_BG		17
#define STAGE_BS_SPOT01		18
#define STAGE_BS_SPOT01_BG		19
#define STAGE_BS_SPOT02		20
//stage.spa内のリソース個数
#define STAGE_SPAMAX	(21)

//roulette.hのsprリソース定義
#define ROULETTE_BR_KEMURI01_L		0
#define ROULETTE_BR_KEMURI01_R		1
#define ROULETTE_BR_KEMURI02_L		2
#define ROULETTE_BR_KEMURI02_R		3
#define ROULETTE_BR_KEMURI03_L		4
#define ROULETTE_BR_KEMURI03_R		5
#define ROULETTE_BR_MIRROR_BLUE		6
#define ROULETTE_BR_MIRROR_BLUEBG		7
#define ROULETTE_BR_MIRROR_RED		8
#define ROULETTE_BR_MIRROR_REDBG		9
#define ROULETTE_BR_MIRROR_WHITE		10
#define ROULETTE_BR_MIRROR_WHITEBG		11
#define ROULETTE_BR_SPOT_GREEN01		12
#define ROULETTE_BR_SPOT_GREEN01BASE		13
#define ROULETTE_BR_SPOT_GREEN02		14
#define ROULETTE_BR_SPOT_GREEN02BASE		15
#define ROULETTE_BR_SPOT_GREEN03		16
#define ROULETTE_BR_SPOT_GREEN03BASE		17
#define ROULETTE_BR_SPOT_GREEN04		18
#define ROULETTE_BR_SPOT_GREEN04BASE		19
#define ROULETTE_BR_SPOT_PINK01		20
#define ROULETTE_BR_SPOT_PINK01BASE		21
#define ROULETTE_BR_SPOT_PINK02		22
#define ROULETTE_BR_SPOT_PINK02BASE		23
#define ROULETTE_BR_SPOT_PINK03		24
#define ROULETTE_BR_SPOT_PINK03BASE		25
#define ROULETTE_BR_SPOT_PINK04		26
#define ROULETTE_BR_SPOT_PINK04BASE		27
#define ROULETTE_BS_LASOR_AO01		28
#define ROULETTE_BS_LASOR_AO02		29
#define ROULETTE_BS_LASOR_AO03		30
#define ROULETTE_BS_LASOR_AO04		31
#define ROULETTE_BS_LASOR_PURPLE01		32
#define ROULETTE_BS_LASOR_PURPLE02		33
#define ROULETTE_BS_LASOR_PURPLE03		34
#define ROULETTE_BS_LASOR_PURPLE04		35
#define ROULETTE_BS_LASOR_RED01		36
#define ROULETTE_BS_LASOR_RED02		37
#define ROULETTE_BS_LASOR_RED03		38
#define ROULETTE_BS_LASOR_RED04		39
#define ROULETTE_BS_LASOR_WHITE01		40
#define ROULETTE_BS_LASOR_WHITE02		41
#define ROULETTE_BS_LASOR_WHITE03		42
#define ROULETTE_BS_LASOR_WHITE04		43
#define ROULETTE_BS_LASOR_YELLOW01		44
#define ROULETTE_BS_LASOR_YELLOW02		45
#define ROULETTE_BS_LASOR_YELLOW03		46
#define ROULETTE_BS_LASOR_YELLOW04		47
//roulette.spa内のリソース個数
#define ROULETTE_SPAMAX	(48)

//roulette_brain.hのsprリソース定義
#define ROULETTE_BRAIN_BR_MIRROR_YELLOW		0
#define ROULETTE_BRAIN_BR_MIRROR_YELLOWBG		1
//roulette_brain.spa内のリソース個数
#define ROULETTE_BRAIN_SPAMAX	(2)

//factory.hのsprリソース定義
#define FACTORY_BF_WARP01		0
#define FACTORY_BF_WARP02		1
#define FACTORY_BF_WARP03		2
//factory.spa内のリソース個数
#define FACTORY_SPAMAX	(3)

//castle.hのsprリソース定義
#define CASTLE_BC_KIRA		0
//castle.spa内のリソース個数
#define CASTLE_SPAMAX	(1)



//---- frontier_particle_lst_tblテーブルのdefine定義 ----
#define SPA_TEST_001		(0)
#define SPA_TEST_002		(1)
#define SPA_STAGE		(2)
#define SPA_ROULETTE		(3)
#define SPA_ROULETTE_BRAIN		(4)
#define SPA_FACTORY		(5)
#define SPA_CASTLE		(6)

#define SPA_FRONTIER_PARTICLE_LST_MAX		(7)


#endif

