//[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[
/**
 *
 *	@file		wifi_p2pmatchroom_map.dat
 *	@brief		wifi	マッチングルーム	マップデータ
 *	@author		tomoya takahashi
 *	@data		2007.03.30
 *
 */
//]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

#define __WIFI_P2PMATCHROOM_MAP_H_GLOBAL
#include "wifi_p2pmatchroom_map.h"

//-----------------------------------------------------------------------------
/**
 *					コーディング規約
 *		●関数名
 *				１文字目は大文字それ以降は小文字にする
 *		●変数名
 *				・変数共通
 *						constには c_ を付ける
 *						staticには s_ を付ける
 *						ポインタには p_ を付ける
 *						全て合わさると csp_ となる
 *				・グローバル変数
 *						１文字目は大文字
 *				・関数内変数
 *						小文字と”＿”と数字を使用する 関数の引数もこれと同じ
*/
//-----------------------------------------------------------------------------

#define MCR_MAP_NUM	(4)

// マップグリッド数
#define MCR_MAP00_GRID_X	(16)
#define MCR_MAP00_GRID_Y	(11)
#define MCR_MAP00_ARRYNUM	( MCR_MAP00_GRID_X*MCR_MAP00_GRID_Y )

#define MCR_MAP01_GRID_X	(16)
#define MCR_MAP01_GRID_Y	(11)
#define MCR_MAP01_ARRYNUM	( MCR_MAP01_GRID_X*MCR_MAP01_GRID_Y )

#define MCR_MAP02_GRID_X	(22)
#define MCR_MAP02_GRID_Y	(11)
#define MCR_MAP02_ARRYNUM	( MCR_MAP02_GRID_X*MCR_MAP02_GRID_Y )

#define MCR_MAP03_GRID_X	(28)
#define MCR_MAP03_GRID_Y	(11)
#define MCR_MAP03_ARRYNUM	( MCR_MAP03_GRID_X*MCR_MAP03_GRID_Y )


//-----------------------------------------------------------------------------
/**
 *		マップデータ
 */
//-----------------------------------------------------------------------------

// マップデータ
static const WF2DMAP_MAP McrMap00Data[MCR_MAP00_ARRYNUM] = {
	// 1行
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, 
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 2行
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, 
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_PC,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 3行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, WCR_MAPDATA_OBJ00, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, WCR_MAPDATA_OBJ04, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 4行
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK,
	// 5行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, WCR_MAPDATA_OBJ01, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, WCR_MAPDATA_OBJ05, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 6行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 7行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, WCR_MAPDATA_OBJ02, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, WCR_MAPDATA_OBJ06, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 8行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 9行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, WCR_MAPDATA_OBJ03, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, WCR_MAPDATA_OBJ07, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 10行
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK,
	// 11行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_EXIT,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
};

static const WF2DMAP_MAP McrMap01Data[MCR_MAP01_ARRYNUM] = {
	// 1行
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, 
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 2行
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, 
	WCR_MAPDATA_PC, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_PC, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 3行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ00, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ04, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ00, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ04, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 4行
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, 
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, 
	WCR_MAPDATA_MAP01, MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK,
	// 5行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ01, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ05, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ01, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ05, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 6行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, 
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, 
	WCR_MAPDATA_MAP01, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 7行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ02, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ06, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ02, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ06, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 8行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, 
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, 
	WCR_MAPDATA_MAP01, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 9行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ03, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ07, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ03, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ07, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 10行
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, 
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, 
	WCR_MAPDATA_MAP01, MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK,
	// 11行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_EXIT,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
};

static const WF2DMAP_MAP McrMap02Data[MCR_MAP02_ARRYNUM] = {
	// 1行
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, 
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 2行
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, 
	WCR_MAPDATA_PC, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_PC, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_PC, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 3行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ00, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ04, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ00, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ04, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ00, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ04, MCR_MAPPM_NONE,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 4行
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, 
	WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK,
	// 5行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ01, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ05, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ01, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ05, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ01, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ05, MCR_MAPPM_NONE,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 6行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, 
	WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, MCR_MAPPM_NONE,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 7行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ02, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ06, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ02, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ06, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ02, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ06, MCR_MAPPM_NONE,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 8行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, 
	WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, MCR_MAPPM_NONE,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 9行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ03, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ07, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ03, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ07, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ03, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ07, MCR_MAPPM_NONE,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 10行
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, 
	WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK,
	// 11行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_EXIT, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
};

static const WF2DMAP_MAP McrMap03Data[MCR_MAP03_ARRYNUM] = {
	// 1行
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, 
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 2行
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, 
	WCR_MAPDATA_PC, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_PC, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_PC, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_PC, WCR_MAPDATA_BLOCK,
	WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 3行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ00, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ04, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ00, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ04, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ00, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ04, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ00, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ04, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 4行
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, 
	WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03,
	WCR_MAPDATA_MAP03, MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK,
	// 5行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ01, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ05, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ01, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ05, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ01, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ05, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ01, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ05, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 6行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, 
	WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03,
	WCR_MAPDATA_MAP03, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 7行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ02, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ06, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ02, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ06, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ02, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ06, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ02, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ06, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 8行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, 
	WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03,
	WCR_MAPDATA_MAP03, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 9行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ03, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ07, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ03, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ07, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ03, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_OBJ07, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ03, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	WCR_MAPDATA_OBJ07, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
	// 10行
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, 
	WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, WCR_MAPDATA_MAP02, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00, WCR_MAPDATA_MAP00,
	WCR_MAPDATA_MAP00, MCR_MAPPM_NONE, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01,
	WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, WCR_MAPDATA_MAP01, MCR_MAPPM_NONE,
	WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03, WCR_MAPDATA_MAP03,
	WCR_MAPDATA_MAP03, MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK,
	// 11行
	WCR_MAPDATA_BLOCK, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, 
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, WCR_MAPDATA_EXIT, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE, MCR_MAPPM_NONE,
	MCR_MAPPM_NONE, MCR_MAPPM_NONE, WCR_MAPDATA_BLOCK, WCR_MAPDATA_BLOCK,
};




//----------------------------------------------------------------------------
/**
 *	@brief	マップのグリッドサイズを取得する
 *
 *	@param	no		マップナンバー
 *
 *	@return	グリッドサイズ
 */
//-----------------------------------------------------------------------------
WF2DMAP_POS WcrMapGridSizGet( u32 no )
{
	static const WF2DMAP_POS WcrMapSiz[ MCR_MAP_NUM ] = {
		{ MCR_MAP00_GRID_X, MCR_MAP00_GRID_Y },
		{ MCR_MAP01_GRID_X, MCR_MAP01_GRID_Y },
		{ MCR_MAP02_GRID_X, MCR_MAP02_GRID_Y },
		{ MCR_MAP03_GRID_X, MCR_MAP03_GRID_Y },
	};
	return WcrMapSiz[no];
}

//----------------------------------------------------------------------------
/**
 *	@brief	マップのデータを取得
 *
 *	@param	no		マップナンバー
 *
 *	@return	マップデータ取得
 */
//-----------------------------------------------------------------------------
const WF2DMAP_MAP* WcrMapDataGet( u32 no )
{
	static const WF2DMAP_MAP* pWcrMapData[ MCR_MAP_NUM ] = {
		McrMap00Data,
		McrMap01Data,
		McrMap02Data,
		McrMap03Data,
	};

	return pWcrMapData[ no ];
}
