REM グラフィッカーが関連づけ設定をされているファイルもコンバートされる
REM cellを使用しないBGはオプション指定をつける
REM nceを指定すると、ncg,nclも合わせてコンバートされる
REM nscを指定すると、ncgも合わせてコンバートされる
REM
REM 共通
g2dcvtr poke.nce
REM 上画面
g2dcvtr u_bg00.nsc
g2dcvtr u_bg01.nsc
g2dcvtr u_bg.ncl
REM 下画面
g2dcvtr l_bg00.nsc
g2dcvtr l_bg01.nsc
g2dcvtr l_bg.ncl
g2dcvtr l_bg01gin.nsc
g2dcvtr l_bg01gin.ncl
g2dcvtr l_oam00.nce
g2dcvtr l_oam01.nce
g2dcvtr l_oam02.nce
g2dcvtr l_oam_waku01.ncl
g2dcvtr l_oam_waku02.ncl
g2dcvtr l_oam_waku03.ncl
g2dcvtr l_oam_waku04.ncl
g2dcvtr l_oam_waku05.ncl
g2dcvtr l_oam_waku06.ncl
g2dcvtr l_oam_waku07.ncl
g2dcvtr l_oam_waku08.ncl
